# Generated by Django 2.0.7 on 2018-07-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180722_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdynamicdetail',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
